version: '3'
services:
  app:
    image: spring-boot-streaming
    ports:
      - 9091:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pulkit@98
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
